kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-rolebinding
  namespace: default 
subjects:
- kind: ServiceAccount
  name: kubeinvaders 
  namespace: default 
roleRef:
  kind: Role
  name: kubeinvaders-role 
  apiGroup: rbac.authorization.k8s.io
